import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";
import { Menu } from "./menu";
import { Logo } from "components/logo";
import { getSessionUser } from "lib/app.next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getSessionUser();

  return (
    <div className={styles.root}>
      <div className={styles.mainNavigation}>
        <Link href="/">
          <Logo />
        </Link>
        <Menu userId={user?._id} />
      </div>
      <div className={styles.content}>{children}</div>
    </div>
  );
}
